#!/usr/bin/env scons

import os

from os.path import join
from nestly.scons import SConsWrap
from nestly import Nest
import SCons.Script as sc

# Command line options

sc.AddOption('--output', type='string', help="output folder", default='_output')
sc.AddOption('--cluster', type='string', help="use cluster?", default='local')

env = sc.Environment(
        ENV=os.environ,
        output=sc.GetOption('output'),
        cluster=sc.GetOption('cluster'),
        )

sc.Export('env')

env.SConsignFile()

flag = 'simulation_null_naive'
sc.SConscript(flag + '/sconscript', exports=['flag'])

flag = 'simulation_null_retrain'
sc.SConscript(flag + '/sconscript', exports=['flag'])

flag = 'simulation_null_score'
sc.SConscript(flag + '/sconscript', exports=['flag'])

flag = 'simulation_null_score_unmeas'
sc.SConscript(flag + '/sconscript', exports=['flag'])

flag = 'simulation_additive_equiconf'
sc.SConscript(flag + '/sconscript', exports=['flag'])

flag = 'simulation_power_magnitude'
sc.SConscript(flag + '/sconscript', exports=['flag'])

flag = 'simulation_power_trust'
sc.SConscript(flag + '/sconscript', exports=['flag'])

flag = 'exp_ponv'
sc.SConscript(flag + '/sconscript', exports=['flag'])
